package com.codeskittles.learning.designpatterns.creational.builder.lombok;

import lombok.Builder;

// Lombok's Builder Annotation
@Builder
public class _02_PhoneBlokWithLombok {

    private final String camera;
    private final String projector;
    private final String processor;
    private final String internalMemory;
    private final String battery;
    private final String displayScreen;

    // No need to write the Builder Implementation. Lombok does it for you,
    // just annotate your type you will have a builder
    public static void main(String[] args) {
        // Client of _02_PhoneBlokWithLombok

        _02_PhoneBlokWithLombok phoneBlok =
                _02_PhoneBlokWithLombok
                        // The methods below were auto generated by Lombok
                        .builder()
                        .processor("Intel i9 10th gen")
                        .internalMemory("16gb Samsung RAM")
                        .battery("4000mAh Battery")
                        .displayScreen("UHD 4K Screen")
                        .projector("Elite Projector 4K")
                        .build();
    }
}
